// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }
export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My E-Commerce Site</title>
        <meta name="description" content="Welcome to our E-Commerce site!" />
        {/* Add other meta tags or links to stylesheets here if needed */}
      </head>
      <body>
        <header>
          <nav>
            <ul className="flex space-x-4">
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="/products">Products</a>
              </li>
              <li>
                <a href="/about">About Us</a>
              </li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
        <footer>
          <p className="text-center">© 2024 My E-Commerce Site</p>
        </footer>
      </body>
    </html>
  );
}

